export const INQUIRY = "/api/inquiry/createInquiry"
export const GET_PRODUCT = "/api/customer/viewProduct"
export const GET_SERVICE = "/api/customer/viewService"
export const GET_PRODUCT_LIST = "/api/customer/getProductList"
export const GET_SERVICES_LIST = "/api/customer/getServiceList"
export const GET_MEMBERS_LIST = "/api/leadership/customer/getMembers"